In [18]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.datasets import load_breast_cancer
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.preprocessing import StandardScaler

In [19]:
df = load_breast_cancer()

In [20]:
df.target_names

array(['malignant', 'benign'], dtype='<U9')

In [21]:
df.feature_names

array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error',
       'fractal dimension error', 'worst radius', 'worst texture',
       'worst perimeter', 'worst area', 'worst smoothness',
       'worst compactness', 'worst concavity', 'worst concave points',
       'worst symmetry', 'worst fractal dimension'], dtype='<U23')

In [22]:
x = df.data
y = df.target

In [23]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.2 , random_state=3)

In [24]:
x_train.shape, x_test.shape

((455, 30), (114, 30))

In [26]:
scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

In [27]:
model = LogisticRegression(max_iter= 500)

In [28]:
model.fit(x_train_scaled, y_train)

,"max_iter max_iter: int, default=100Maximum number of iterations taken for the solvers to converge.",500
,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add an L2 penalty term and it is the default choice;- `'l1'`: add an L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` and `C` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'`, `l1_ratio` set to any float between 0 and 1 for `penalty='elasticnet'`, and `C=np.inf` for `penalty=None`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation <regularized-logistic-loss>`) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary <random_state>` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'l

In [29]:
ypred = model.predict(x_test_scaled)

In [30]:
print(classification_report(y_test, ypred))

              precision    recall  f1-score   support

           0       0.97      0.95      0.96        40
           1       0.97      0.99      0.98        74

    accuracy                           0.97       114
   macro avg       0.97      0.97      0.97       114
weighted avg       0.97      0.97      0.97       114



In [31]:
print(confusion_matrix(y_test, ypred))
# Actual vs predicted
# TP TN FP FN

[[38  2]
 [ 1 73]]


## practice questions

In [45]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

# Load Iris
data = load_iris()

x = data.data
y = data.target

# Split
x_train, x_test, y_train, y_test = train_test_split(
    x, y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

# NEW model
model = Pipeline([
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression(max_iter=500))
])

# Train
model.fit(x_train, y_train)

# Predict
y_pred = model.predict(x_test)
y_prob = model.predict_proba(x_test)

In [46]:
from sklearn.metrics import confusion_matrix, classification_report

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

[[10  0  0]
 [ 0  9  1]
 [ 0  1  9]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.90      0.90      0.90        10
           2       0.90      0.90      0.90        10

    accuracy                           0.93        30
   macro avg       0.93      0.93      0.93        30
weighted avg       0.93      0.93      0.93        30



In [47]:
print(y_prob[:5])

[[9.78818005e-01 2.11816311e-02 3.63821812e-07]
 [3.79836951e-03 3.69220168e-01 6.26981463e-01]
 [1.48799040e-01 8.42474895e-01 8.72606441e-03]
 [9.54449962e-02 8.94618634e-01 9.93636953e-03]
 [9.88493051e-01 1.15067767e-02 1.72549650e-07]]


In [53]:
y_pred = model.predict(x_test)

y_prob = model.predict_proba(x_test)

print("y_pred:", y_pred.shape)
print("y_prob:", y_prob.shape)

y_pred: (30,)
y_prob: (30, 3)


In [54]:
from sklearn.metrics import roc_auc_score

auc = roc_auc_score(
    y_test,
    y_prob,
    multi_class="ovr"
)

print("ROC-AUC:", auc)

ROC-AUC: 0.9966666666666667


# Logistic Regression — Complete Notes

## 1. What is Logistic Regression?

**Logistic Regression** is a **supervised machine learning algorithm used primarily for classification**.

It predicts the probability that an observation belongs to a class.

For binary classification:

```text
Class 0
Class 1
```

Examples:

* Spam / Not Spam
* Disease / No Disease
* Fraud / Not Fraud
* Customer Churn / No Churn

### Why not Linear Regression?

Linear Regression produces unrestricted numerical outputs:

```text
-5
0.7
2.3
105
```

A probability must lie between:

$$
0 \leq p \leq 1
$$

Logistic Regression solves this by passing a linear score through the **sigmoid function**.

---

# 2. Complete Logistic Regression Workflow

```text
Features X
    ↓
Linear Score
z = wX + b
    ↓
Sigmoid
p = 1 / (1 + e⁻ᶻ)
    ↓
Probability
    ↓
Threshold
    ↓
Predicted Class
```

For example:

```text
Probability = 0.82
Threshold   = 0.50
                ↓
Predicted class = 1
```

---

# 3. Linear Score

Logistic Regression first calculates:

$$
z=w_1x_1+w_2x_2+\cdots+w_nx_n+b
$$

where:

* \(x_i\) = feature
* \(w_i\) = learned coefficient
* \(b\) = intercept
* \(z\) = linear score

Example:

$$
z=2x_1-0.5x_2+1
$$

**Important:** \(z\) itself is **not the probability**.

---

# 4. Sigmoid Function ⭐

The sigmoid converts the linear score into a value between 0 and 1.

$$
\sigma(z)=\frac{1}{1+e^{-z}}
$$

Therefore:

$$
p=P(y=1|X)
$$

### Behavior

| \(z\) | Sigmoid |
| ----: | ------: |
|    -2 | ≈ 0.119 |
|    -1 | ≈ 0.269 |
|     0 |   0.500 |
|     1 | ≈ 0.731 |
|     2 | ≈ 0.881 |

So:

```text
z < 0  → p < 0.5
z = 0  → p = 0.5
z > 0  → p > 0.5
```

### Python

```python
import numpy as np

z = np.array([-2, -1, 0, 1, 2])

probability = 1 / (1 + np.exp(-z))
print(probability)
```

---

# 5. Probability vs Class

Logistic Regression produces a **probability**, but we usually need a class.

The default threshold is generally:

$$
threshold=0.5
$$

```text
p < 0.5 → class 0
p ≥ 0.5 → class 1
```

Example:

```text
0.20 → 0
0.45 → 0
0.51 → 1
0.90 → 1
```

### Important

**0.5 is a default, not a universal rule.**

The threshold can be changed depending on the business/problem requirements.

---

# 6. Decision Boundary

At the default threshold:

$$
p=0.5
$$

Since:

$$
\sigma(0)=0.5
$$

the decision boundary occurs when:

$$
z=0
$$

Therefore:

$$
w_1x_1+w_2x_2+\cdots+w_nx_n+b=0
$$

For two features, this produces a **linear decision boundary**.

### Mental model

```text
Probability < 0.5
        ↓
     Class 0

------------------  ← decision boundary

Probability > 0.5
        ↓
     Class 1
```

Logistic Regression is therefore a **linear classifier**.

---

# 7. `predict()` vs `predict_proba()`

### `predict()`

Returns final classes:

```python
y_pred = model.predict(x_test)
```

Example:

```text
[0, 1, 1, 0, 1]
```

### `predict_proba()`

Returns probabilities:

```python
y_prob = model.predict_proba(x_test)
```

Binary classification:

```text
[
 [0.80, 0.20],
 [0.10, 0.90],
 [0.65, 0.35]
]
```

Columns represent:

```text
[P(class 0), P(class 1)]
```

Usually the class with the highest probability becomes the prediction.

---

# 8. Logistic Regression Mathematics

The complete model is:

### Step 1 — Linear score

$$
z=wX+b
$$

### Step 2 — Sigmoid

$$
p=\frac{1}{1+e^{-z}}
$$

### Step 3 — Log loss

For one observation:

$$
Loss=-[y\log(p)+(1-y)\log(1-p)]
$$

The model learns the coefficients that minimize the classification loss over the training data.

---

# 9. Log Loss ⭐

Log Loss is the main loss function used for binary Logistic Regression.

For:

$$
y=1
$$

the loss becomes:

$$
-\log(p)
$$

So:

```text
p = 0.95 → small loss
p = 0.20 → large loss
```

For:

$$
y=0
$$

the loss becomes:

$$
-\log(1-p)
$$

So:

```text
p = 0.05 → small loss
p = 0.99 → huge loss
```

### Core intuition

**Log Loss heavily punishes confident wrong predictions.**

For example:

```text
Actual = 1

Prediction probability = 0.99 → excellent
Prediction probability = 0.51 → okay
Prediction probability = 0.01 → terrible
```

### Important comparison

| Algorithm           | Common loss/objective |
| ------------------- | --------------------- |
| Linear Regression   | MSE / squared error   |
| Logistic Regression | Log Loss              |
| Ridge               | MSE + L2 penalty      |

---

# 10. Confusion Matrix ⭐⭐⭐

For binary classification:

|                 | Actual 0 | Actual 1 |
| --------------- | -------: | -------: |
| **Predicted 0** |       TN |       FN |
| **Predicted 1** |       FP |       TP |

### TP — True Positive

Actual 1, predicted 1.

### TN — True Negative

Actual 0, predicted 0.

### FP — False Positive

Actual 0, predicted 1.

A **false alarm**.

### FN — False Negative

Actual 1, predicted 0.

A **missed positive**.

---

# 11. Accuracy

$$
Accuracy=
\frac{TP+TN}{TP+TN+FP+FN}
$$

It tells us:

> What fraction of all predictions were correct?

Example:

```text
95 correct out of 100
```

$$
Accuracy=0.95
$$

or:

```text
95%
```

### ⚠️ Problem

Accuracy can be misleading with **imbalanced datasets**.

---

# 12. Precision

$$
Precision=
\frac{TP}{TP+FP}
$$

It answers:

> Of everything the model predicted as positive, how many were actually positive?

Example:

```text
Model predicts 100 people have disease
80 actually have disease
```

$$
Precision=0.80
$$

High precision means **few false positives**.

### Think:

> "When the model says YES, can I trust it?"

---

# 13. Recall

$$
Recall=
\frac{TP}{TP+FN}
$$

It answers:

> Of all the actual positives, how many did the model successfully find?

Example:

```text
100 actual patients
90 detected
```

$$
Recall=0.90
$$

High recall means **few false negatives**.

### Think:

> "Did we catch most of the positives?"

---

# 14. F1 Score

$$
F1=
2\frac{Precision\times Recall}
{Precision+Recall}
$$

F1 balances precision and recall.

Useful when both:

* False positives matter
* False negatives matter

---

# 15. Precision vs Recall

This is extremely important in real-world ML.

### Lower threshold

Generally:

```text
Threshold ↓
     ↓
More predicted positives
     ↓
FN ↓
Recall ↑
FP may ↑
```

### Higher threshold

Generally:

```text
Threshold ↑
     ↓
Fewer predicted positives
     ↓
FP ↓
Precision may ↑
FN may ↑
```

There is a **trade-off**.

### Example: disease detection

If missing a genuinely sick patient is extremely dangerous:

```text
FN is very costly
        ↓
Prioritize recall
        ↓
Often use a lower threshold
```

But don't blindly maximize recall—the actual cost of FP and FN determines the appropriate threshold.

---

# 16. Feature Scaling ⭐

Logistic Regression generally benefits from feature scaling.

Suppose:

```text
Age       → 20–80
Salary    → 20,000–2,00,000
Experience → 0–30
```

The different scales can make optimization and regularization less convenient.

A common method is **Standardization**:

$$
z=\frac{x-\mu}{\sigma}
$$

where:

* \(\mu\) = training mean
* \(\sigma\) = training standard deviation

---

## Correct scaling workflow

```python
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

scaler = StandardScaler()

x_train_scaled = scaler.fit_transform(x_train)
x_test_scaled = scaler.transform(x_test)

model = LogisticRegression(max_iter=500)

model.fit(x_train_scaled, y_train)

y_pred = model.predict(x_test_scaled)
```

### ⚠️ Never do this

```python
x_test_scaled = scaler.fit_transform(x_test)
```

Because that learns preprocessing statistics from the test set.

That is a form of **data leakage**.

---

# 17. Pipeline ⭐

A cleaner approach is:

```python
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

model = Pipeline([
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression(max_iter=500))
])

model.fit(x_train, y_train)

y_pred = model.predict(x_test)
```

The pipeline ensures preprocessing is applied correctly.

---

# 18. Which Algorithms Usually Need Scaling?

| Algorithm           | Scaling?                |
| ------------------- | ----------------------- |
| Logistic Regression | ✅ Generally recommended |
| Ridge               | ✅ Generally recommended |
| Lasso               | ✅ Generally recommended |
| SVM                 | ✅ Yes                   |
| KNN                 | ✅ Yes                   |
| Decision Tree       | ❌ Usually unnecessary   |
| Random Forest       | ❌ Usually unnecessary   |

### Easy rule

**Distance-based, optimization-based, or regularized models → scaling often matters.**

Tree-based models generally don't care about feature magnitude because they make threshold-based splits.

---

# 19. Regularization ⭐

Regularization helps control overly large coefficients and can improve generalization.

Conceptually, Logistic Regression with L2 regularization minimizes:

$$
LogLoss+\lambda\sum_jw_j^2
$$

The penalty discourages large coefficients.

### L2

Shrinks coefficients toward zero.

Usually:

```text
Coefficient ≠ exactly 0
```

### L1

Can push some coefficients exactly to zero.

This can perform feature selection.

---

# 20. Logistic Regression `C`

In scikit-learn:

```python
LogisticRegression(C=...)
```

`C` is the **inverse of regularization strength**.

Therefore:

```text
C ↓ → stronger regularization
C ↑ → weaker regularization
```

Compare with Ridge:

```text
Ridge:
alpha ↑ → stronger regularization

Logistic Regression:
C ↓ → stronger regularization
```

This difference is extremely important to remember.

---

# 21. ROC Curve

The ROC curve evaluates the model across different classification thresholds.

It plots:

$$
TPR \quad vs \quad FPR
$$

where:

$$
TPR=Recall=\frac{TP}{TP+FN}
$$

and:

$$
FPR=\frac{FP}{FP+TN}
$$

The model is evaluated at **many thresholds**, not just 0.5.

---

# 22. ROC-AUC ⭐

ROC-AUC = Area Under the ROC Curve.

It measures how well the model **separates/ranks positive and negative examples across thresholds**.

Rough intuition:

|   AUC | Interpretation            |
| ----: | ------------------------- |
|   1.0 | Perfect separation        |
|   0.9 | Excellent                 |
|   0.8 | Good                      |
|   0.5 | Random-like               |
| < 0.5 | Worse than random ranking |

### ⚠️ AUC is NOT accuracy.

For example:

```text
Accuracy = 93.3%
ROC-AUC  = 99.67%
```

These measure different things.

---

# 23. Why ROC-AUC Uses Probabilities

Use:

```python
y_prob = model.predict_proba(x_test)[:, 1]
```

then:

```python
from sklearn.metrics import roc_auc_score

auc = roc_auc_score(y_test, y_prob)
```

Don't normally use:

```python
roc_auc_score(y_test, y_pred)
```

because:

```text
predict()
     ↓
0 / 1
```

only gives one threshold's decisions.

ROC-AUC needs scores/probabilities so it can evaluate the model over many thresholds.

---

# 24. Class Imbalance ⭐⭐⭐

Suppose:

```text
990 healthy
10 sick
```

A terrible model could predict:

```text
Everyone = healthy
```

Accuracy:

$$
\frac{990}{1000}=99\%
$$

Looks excellent—but:

```text
Recall for sick patients = 0
```

The model found **none** of the sick people.

Therefore, with imbalanced classification, don't rely only on accuracy.

Consider:

* Precision
* Recall
* F1
* Confusion matrix
* ROC-AUC
* PR-AUC

---

# 25. PR-AUC

PR-AUC refers to the area under the **Precision-Recall curve**.

It can be particularly useful when the positive class is **very rare**.

Why?

Because Precision-Recall focuses directly on:

```text
Precision
Recall
```

which are often more informative than accuracy in rare-positive problems.

---

# 26. Multiclass Logistic Regression

Logistic Regression can also handle multiple classes.

Example:

```text
0 → Setosa
1 → Versicolor
2 → Virginica
```

`predict_proba()` can return:

```text
[
 [0.98, 0.02, 0.00],
 [0.01, 0.37, 0.62],
 [0.15, 0.84, 0.01]
]
```

Each row contains probabilities for the classes.

For example:

```text
[0.01, 0.37, 0.62]
```

means:

```text
Class 0 → 1%
Class 1 → 37%
Class 2 → 62%
```

Prediction:

```text
Class 2
```

because it has the highest probability.

---

# 27. Multiclass ROC-AUC

For multiclass ROC-AUC, you need to specify a strategy such as:

```python
auc = roc_auc_score(
    y_test,
    y_prob,
    multi_class="ovr"
)
```

`ovr` means:

**One-vs-Rest**

For example:

```text
Class 0 vs all others
Class 1 vs all others
Class 2 vs all others
```

---

# 28. `stratify=y`

When splitting classification data:

```python
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)
```

`stratify=y` attempts to preserve the original class distribution in both train and test sets.

Example:

```text
Original:
Class 0 → 33%
Class 1 → 33%
Class 2 → 34%

Train:
≈ 33 / 33 / 34%

Test:
≈ 33 / 33 / 34%
```

### Why?

Without stratification, random sampling can accidentally produce an unrepresentative class distribution, especially with:

* small datasets
* imbalanced datasets

It **doesn't make the model itself better**.

It makes the train/test split more representative.

---

# 29. Logistic Regression Assumptions

### 1. Independent observations

Observations should generally be independent.

Repeated/dependent observations may require methods that account for that dependency.

---

### 2. Linear relationship between predictors and log-odds ⭐

This is a key Logistic Regression assumption.

Logistic Regression assumes:

$$
\log\left(\frac{p}{1-p}\right)
=
wX+b
$$

The predictors should have an approximately linear relationship with the **log-odds**, not necessarily directly with probability.

---

### 3. No severe multicollinearity

Highly correlated predictors can make coefficients unstable and difficult to interpret.

Example:

```text
Age
Years of Experience
```

with:

$$
correlation=0.97
$$

may cause concern.

---

### 4. No perfect separation

If a feature perfectly separates the classes:

```text
X < 10 → class 0
X > 10 → class 1
```

Logistic Regression can produce extremely large coefficients and estimation problems.

Regularization can help in practical implementations.

---

### 5. Sufficient representative data

There should be enough useful observations to estimate the model reliably, especially when:

* there are many features
* classes are rare
* the dataset is small

---

# 30. Logistic Regression Coefficients ⭐⭐⭐

This is an important distinction from Linear Regression.

Logistic Regression models:

$$
\log\left(\frac{p}{1-p}\right)
=
b+w_1x_1+\cdots+w_nx_n
$$

The coefficient directly represents a change in **log-odds**, not probability.

### ❌ Incorrect

> A coefficient of 0.7 means probability increases by 70%.

Not correct.

---

# 31. Odds

Odds are:

$$
Odds=\frac{p}{1-p}
$$

If:

$$
p=0.8
$$

then:

$$
Odds=\frac{0.8}{0.2}=4
$$

So:

```text
Probability = 80%
Odds = 4:1
```

---

# 32. Log-Odds

Log-odds are:

$$
\log\left(\frac{p}{1-p}\right)
$$

Logistic Regression models this quantity linearly:

$$
logOdds=wX+b
$$

---

# 33. Odds Ratio

Exponentiating a coefficient gives its **odds ratio**:

$$
OR=e^{w_j}
$$

Suppose:

$$
w_j=0.693
$$

Then:

$$
e^{0.693}\approx2
$$

Interpretation:

> A one-unit increase in that feature is associated with approximately **2× the odds of the positive class**, holding other features constant.

### Positive coefficient

$$
w>0
$$

→ odds increase.

### Negative coefficient

$$
w<0
$$

→ odds decrease.

### Zero coefficient

$$
w=0
$$

$$
e^0=1
$$

→ no change in odds.

---

# 34. Odds ≠ Probability

Keep these separate:

$$
Probability=p
$$

$$
Odds=\frac{p}{1-p}
$$

$$
LogOdds=\log\left(\frac{p}{1-p}\right)
$$

Example:

$$
p=0.8
$$

gives:

```text
Probability = 0.80
Odds        = 4
Log-odds    ≈ 1.386
```

---

# 35. Complete Python Implementation

A clean binary Logistic Regression workflow:

```python
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    confusion_matrix,
    classification_report,
    roc_auc_score
)

x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

model = Pipeline([
    ("scaler", StandardScaler()),
    ("classifier", LogisticRegression(max_iter=500))
])

model.fit(x_train, y_train)

y_pred = model.predict(x_test)
y_prob = model.predict_proba(x_test)[:, 1]

print(confusion_matrix(y_test, y_pred))
print(classification_report(y_test, y_pred))

auc = roc_auc_score(y_test, y_prob)
print("ROC-AUC:", auc)
```

---

# 36. Common Mistakes 🚨

### Mistake 1

Using Linear Regression for classification.

❌

Use:

```python
LogisticRegression()
```

---

### Mistake 2

Thinking sigmoid output is automatically the final class.

❌

It is a probability.

```text
Sigmoid → probability
Threshold → class
```

---

### Mistake 3

Thinking 0.5 is always the correct threshold.

❌

Threshold depends on the cost of FP/FN.

---

### Mistake 4

Using `predict()` for ROC-AUC.

❌

Use probabilities/scores:

```python
model.predict_proba(x_test)[:, 1]
```

---

### Mistake 5

Scaling test data independently.

❌

```python
scaler.fit_transform(x_test)
```

Use:

```python
scaler.transform(x_test)
```

---

### Mistake 6

Using only accuracy on an imbalanced dataset.

❌

Check:

```text
Confusion Matrix
Precision
Recall
F1
ROC-AUC
PR-AUC
```

---

### Mistake 7

Confusing precision and recall.

Remember:

```text
Precision → predicted positives → how many correct?

Recall → actual positives → how many found?
```

---

### Mistake 8

Thinking coefficient = probability change.

❌

Logistic coefficient → **log-odds change**.

$$
e^{coefficient}
$$

→ odds ratio.

---

### Mistake 9

Thinking multicollinearity automatically means bad predictions.

❌

Its major issue is often **unstable/difficult coefficient interpretation**.

---

### Mistake 10

Reusing an already-fitted model on data with a different number of features.

For example:

```text
Breast Cancer → 30 features
Iris → 4 features
```

A model fitted on one cannot directly accept the other.

Create and fit the appropriate model again.

---

# 37. Logistic Regression vs Linear Regression vs Ridge

|                    | Linear Regression | Ridge               | Logistic Regression       |
| ------------------ | ----------------- | ------------------- | ------------------------- |
| Task               | Regression        | Regression          | Classification            |
| Target             | Continuous        | Continuous          | Class                     |
| Main output        | Numerical value   | Numerical value     | Probability/class         |
| Core function      | Linear            | Linear              | Linear + sigmoid          |
| Common loss        | MSE               | MSE + L2            | Log Loss + regularization |
| Regularization     | ❌                 | L2                  | L1/L2                     |
| Scaling            | Sometimes         | Generally important | Generally recommended     |
| Output probability | ❌                 | ❌                   | ✅                         |

---

# 38. Interview-Level Mental Model ⭐

If an interviewer asks:

> **Explain Logistic Regression.**

A strong answer:

> "Logistic Regression is a supervised classification algorithm. It first calculates a linear score from the input features, passes that score through the sigmoid function to obtain a probability for the positive class, and then applies a decision threshold to obtain the final class. During training, it learns the coefficients by minimizing log loss, typically with regularization. Its performance can be evaluated using metrics such as precision, recall, F1, confusion matrix, and ROC-AUC."

---

# 39. One-Page Mental Map 🧠

```text
                 LOGISTIC REGRESSION
                         │
                         ▼
                Classification
                         │
                         ▼
                  Linear Score
                   z = wX + b
                         │
                         ▼
                     Sigmoid
                  1 / (1 + e⁻ᶻ)
                         │
                         ▼
                   Probability
                         │
                  ┌──────┴──────┐
                  ▼             ▼
             predict()     predict_proba()
                  │             │
                  ▼             ▼
               Class       Probability
                  │
                  ▼
              Threshold
                  │
                  ▼
          Decision Boundary
             wX + b = 0
```

Training:

```text
X + y
 ↓
Linear score
 ↓
Sigmoid
 ↓
Probability
 ↓
Log Loss
 ↓
Optimization
 ↓
Learn coefficients
```

Evaluation:

```text
Confusion Matrix
       ↓
 ┌─────┼────────┐
 ▼     ▼        ▼
Precision Recall Accuracy
       │
       ▼
      F1
       │
       ▼
ROC-AUC / PR-AUC
```

Model quality:

```text
Scaling
   +
Regularization
   +
Correct threshold
   +
Proper evaluation
   +
No leakage
   +
Good assumptions
   ↓
Better generalization
```

Coefficient interpretation:

```text
Coefficient
     ↓
  Log-Odds
     ↓
 exp(coefficient)
     ↓
 Odds Ratio
```

## ✅ Logistic Regression Status

You have now covered the **full practical Logistic Regression block**:

* Why Logistic Regression
* Linear score
* Sigmoid
* Probability
* Classification threshold
* Decision boundary
* Log loss
* Confusion matrix
* Accuracy
* Precision
* Recall
* F1
* Threshold trade-offs
* Feature scaling
* Pipelines
* Regularization
* L1/L2
* `C`
* ROC curve
* ROC-AUC
* PR-AUC
* Class imbalance
* Multiclass classification
* OvR
* `stratify=y`
* Logistic Regression assumptions
* Coefficients
* Log-odds
* Odds
* Odds ratios
* Implementation
* Common mistakes
* Interview understanding

