In [1]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [2]:
iris = load_iris()

x = iris.data
y = iris.target

In [3]:
print(x.shape)
print(y.shape)

(150, 4)
(150,)


In [4]:
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

In [5]:
pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("knn", KNeighborsClassifier(n_neighbors=5))
])

In [6]:
pipeline.fit(x_train, y_train)

,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators <combining_estimators>` for more details.","[('scaler', ...), ('knn', ...)]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing <metadata_routing>`.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
Name,Type,Value
"classes_ classes_: ndarray of shape (n_classes,)The classes labels. Only exist if the last step of the pipeline is aclassifier.","ndarray[int64](3,)","[0,1,2]"
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`. Only defined if theunderlying first estimator in `steps` exposes such an attributewhen fit... versionadded:: 0.24,int,4
,"copy copy: bool, default=TrueIf False, try to avoid a copy and do inplace scaling instead.This is not guaranteed to always work inplace; e.g. if the data isnot a NumPy array or scipy.sparse CSR matrix, a copy may still bereturned.",True
,"with_mean with_mean: bool, default=TrueIf True, center the data before scaling.This does not work (and will raise an exception) when attempted onsparse matrices, because centering them entails building a densematrix which in common use cases is likely to be too large to fit inmemory.",True
,"with_std with_std: bool, default=TrueIf True, scale the data to unit variance (or equivalently,unit standard deviation).",True
Name,Type,Value


In [7]:
y_train_pred = pipeline.predict(x_train)
y_pred = pipeline.predict(x_test)

In [8]:
train_accuracy = accuracy_score(y_train, y_train_pred)
test_accuracy = accuracy_score(y_test, y_pred)

print(f"Train Accuracy: {train_accuracy:.4f}")
print(f"Test Accuracy: {test_accuracy:.4f}")

Train Accuracy: 0.9750
Test Accuracy: 0.9333


In [9]:
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Confusion Matrix:
[[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.83      1.00      0.91        10
           2       1.00      0.80      0.89        10

    accuracy                           0.93        30
   macro avg       0.94      0.93      0.93        30
weighted avg       0.94      0.93      0.93        30



In [10]:
k_values = [1, 3, 5, 7, 9, 11, 15, 21]

for k in k_values:

    pipeline = Pipeline([
        ("scaler", StandardScaler()),
        ("knn", KNeighborsClassifier(n_neighbors=k))
    ])

    pipeline.fit(x_train, y_train)

    y_train_pred = pipeline.predict(x_train)
    y_pred = pipeline.predict(x_test)

    train_accuracy = accuracy_score(y_train, y_train_pred)
    test_accuracy = accuracy_score(y_test, y_pred)

    print(
        f"K={k:<3} | "
        f"Train Accuracy={train_accuracy:.4f} | "
        f"Test Accuracy={test_accuracy:.4f}"
    )

K=1   | Train Accuracy=1.0000 | Test Accuracy=0.9667
K=3   | Train Accuracy=0.9583 | Test Accuracy=0.9333
K=5   | Train Accuracy=0.9750 | Test Accuracy=0.9333
K=7   | Train Accuracy=0.9750 | Test Accuracy=0.9667
K=9   | Train Accuracy=0.9583 | Test Accuracy=0.9667
K=11  | Train Accuracy=0.9583 | Test Accuracy=0.9667
K=15  | Train Accuracy=0.9667 | Test Accuracy=0.9667
K=21  | Train Accuracy=0.9500 | Test Accuracy=0.9667


In [11]:
# Regression

In [12]:
import numpy as np

from sklearn.datasets import make_regression
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error, r2_score

In [13]:
x, y = make_regression(
    n_samples=500,
    n_features=5,
    noise=20,
    random_state=42
)

In [14]:
x_train, x_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42
)

In [15]:
pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("knn", KNeighborsRegressor(n_neighbors=5))
])

In [17]:
pipeline.fit(x_train, y_train)

,"steps steps: list of tuplesList of (name of step, estimator) tuples that are to be chained insequential order. To be compatible with the scikit-learn API, all stepsmust define `fit`. All non-last steps must also define `transform`. See:ref:`Combining Estimators <combining_estimators>` for more details.","[('scaler', ...), ('knn', ...)]"
,"transform_input transform_input: list of str, default=NoneThe names of the :term:`metadata` parameters that should be transformed by thepipeline before passing it to the step consuming it.This enables transforming some input arguments to ``fit`` (other than ``X``)to be transformed by the steps of the pipeline up to the step which requiresthem. Requirement is defined via :ref:`metadata routing <metadata_routing>`.For instance, this can be used to pass a validation set through the pipeline.You can only set this if metadata routing is enabled, which youcan enable using ``sklearn.set_config(enable_metadata_routing=True)``... versionadded:: 1.6",None
,"memory memory: str or object with the joblib.Memory interface, default=NoneUsed to cache the fitted transformers of the pipeline. The last stepwill never be cached, even if it is a transformer. By default, nocaching is performed. If a string is given, it is the path to thecaching directory. Enabling caching triggers a clone of the transformersbefore fitting. Therefore, the transformer instance given to thepipeline cannot be inspected directly. Use the attribute ``named_steps``or ``steps`` to inspect estimators within the pipeline. Caching thetransformers is advantageous when fitting is time consuming. See:ref:`sphx_glr_auto_examples_neighbors_plot_caching_nearest_neighbors.py`for an example on how to enable caching.",None
,"verbose verbose: bool, default=FalseIf True, the time elapsed while fitting each step will be printed as itis completed.",False
Name,Type,Value
n_features_in_ n_features_in_: intNumber of features seen during :term:`fit`. Only defined if theunderlying first estimator in `steps` exposes such an attributewhen fit... versionadded:: 0.24,int,5
,"copy copy: bool, default=TrueIf False, try to avoid a copy and do inplace scaling instead.This is not guaranteed to always work inplace; e.g. if the data isnot a NumPy array or scipy.sparse CSR matrix, a copy may still bereturned.",True
,"with_mean with_mean: bool, default=TrueIf True, center the data before scaling.This does not work (and will raise an exception) when attempted onsparse matrices, because centering them entails building a densematrix which in common use cases is likely to be too large to fit inmemory.",True
,"with_std with_std: bool, default=TrueIf True, scale the data to unit variance (or equivalently,unit standard deviation).",True
Name,Type,Value
"mean_ mean_: ndarray of shape (n_features,) or NoneThe mean value for each feature in the training set.Equal to ``None`` when ``with_mean=False`` and ``with_std=False``.","ndarray[float64](5,)","[0.02,0. ,0.06,0.01,0. ]"


In [18]:
y_train_pred = pipeline.predict(x_train)
y_pred = pipeline.predict(x_test)

In [19]:
train_r2 = r2_score(y_train, y_train_pred)
test_r2 = r2_score(y_test, y_pred)

mse = mean_squared_error(y_test, y_pred)

print(f"Train R2: {train_r2:.4f}")
print(f"Test R2: {test_r2:.4f}")
print(f"MSE: {mse:.4f}")

Train R2: 0.9117
Test R2: 0.8562
MSE: 1745.1293


In [20]:
k_values = [1, 3, 5, 7, 9, 11, 15, 21]

for k in k_values:

    pipeline = Pipeline([
        ("scaler", StandardScaler()),
        ("knn", KNeighborsRegressor(n_neighbors=k))
    ])

    pipeline.fit(x_train, y_train)

    y_train_pred = pipeline.predict(x_train)
    y_pred = pipeline.predict(x_test)

    train_r2 = r2_score(y_train, y_train_pred)
    test_r2 = r2_score(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)

    print(
        f"K={k:<3} | "
        f"Train R2={train_r2:.4f} | "
        f"Test R2={test_r2:.4f} | "
        f"MSE={mse:.4f}"
    )

K=1   | Train R2=1.0000 | Test R2=0.7302 | MSE=3274.7683
K=3   | Train R2=0.9302 | Test R2=0.8432 | MSE=1903.7414
K=5   | Train R2=0.9117 | Test R2=0.8562 | MSE=1745.1293
K=7   | Train R2=0.8969 | Test R2=0.8477 | MSE=1848.4222
K=9   | Train R2=0.8864 | Test R2=0.8437 | MSE=1896.9352
K=11  | Train R2=0.8758 | Test R2=0.8349 | MSE=2004.0918
K=15  | Train R2=0.8588 | Test R2=0.8226 | MSE=2153.1242
K=21  | Train R2=0.8371 | Test R2=0.8071 | MSE=2341.8052


# K-Nearest Neighbors (KNN)

## 1. Definition

**K-Nearest Neighbors (KNN)** is a supervised learning algorithm that makes predictions based on the **closest training samples**.

Core idea:

> **Similar data points tend to have similar outputs.**

KNN is a **distance-based** and **instance-based (lazy learning)** algorithm.

Unlike models such as Linear Regression or Decision Trees, KNN does not learn an explicit equation or tree structure during training. It primarily stores the training data and uses it during prediction.

---

## 2. How KNN Works

For a new data point:

```text
New data point
      ↓
Calculate distance to training points
      ↓
Find K nearest neighbors
      ↓
Make prediction
```

The prediction depends on the problem:

```text
Classification → Majority vote
Regression     → Average target values
```

---

## 3. What is K?

`K` represents the **number of nearest neighbors** considered.

Example:

```python
KNeighborsClassifier(n_neighbors=5)
```

means the model considers the **5 closest training samples**.

### Classification Example

```text
K = 5

A
A
B
A
B

A = 3
B = 2

Prediction → A
```

KNN classification uses **majority voting**.

### Regression Example

```text
K = 3

100
120
110

Prediction = (100 + 120 + 110) / 3
           = 110
```

KNN regression generally uses the **average target value** of the neighbors.

---

# 4. Distance Metrics

KNN determines "nearest" using a **distance metric**.

## Euclidean Distance ⭐

The most commonly used distance metric.

For two points:

$$
A=(x_1,y_1)
$$

$$
B=(x_2,y_2)
$$

Euclidean distance:

$$
d(A,B)=\sqrt{(x_2-x_1)^2+(y_2-y_1)^2}
$$

It represents the **straight-line distance** between two points.

---

## Manhattan Distance

Manhattan distance measures the total movement along each dimension.

$$
d(A,B)=|x_2-x_1|+|y_2-y_1|
$$

Example:

```python
KNeighborsClassifier(
    n_neighbors=5,
    metric="manhattan"
)
```

Common metrics to understand:

```text
Euclidean
Manhattan
```

---

# 5. Feature Scaling ⭐⭐⭐

KNN is a **distance-based algorithm**, so feature scaling is extremely important.

Suppose:

```text
Age     → 20–80
Salary  → 20,000–200,000
```

Salary has a much larger numerical range and can dominate the distance calculation.

Therefore, we generally scale the features before KNN.

```text
Original features
       ↓
StandardScaler
       ↓
KNN
```

A Pipeline is preferred:

```python
pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("knn", KNeighborsClassifier(n_neighbors=5))
])
```

This also helps prevent **data leakage**, because the scaler is fitted using the training data within the pipeline.

---

# 6. KNN Classification

For classification:

```python
from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier(
    n_neighbors=5
)
```

Workflow:

```text
New sample
    ↓
Calculate distances
    ↓
Find K nearest samples
    ↓
Majority voting
    ↓
Predicted class
```

Evaluation metrics can include:

* Accuracy
* Precision
* Recall
* F1-score
* Confusion Matrix

---

# 7. KNN Regression

For regression:

```python
from sklearn.neighbors import KNeighborsRegressor

model = KNeighborsRegressor(
    n_neighbors=5
)
```

Workflow:

```text
New sample
    ↓
Calculate distances
    ↓
Find K nearest samples
    ↓
Average target values
    ↓
Predicted numerical value
```

Evaluation metrics can include:

* MSE
* RMSE
* R²

---

# 8. Effect of K

Choosing K creates a **bias-variance trade-off**.

## Small K

Example:

```text
K = 1
```

The model is highly sensitive to individual training samples.

Characteristics:

* More flexible
* Lower bias
* Higher variance
* Higher risk of overfitting

```text
Small K
   ↓
High variance
   ↓
Overfitting risk
```

## Large K

Example:

```text
K = 50
```

The model considers many neighbors.

Characteristics:

* Smoother predictions
* Higher bias
* Lower variance
* Too large → underfitting

```text
Large K
   ↓
High bias
   ↓
Underfitting risk
```

### Important

Don't say:

> K=1 always overfits.

Instead:

> **Small K has a higher risk of overfitting because it is highly sensitive to individual training samples.**

---

# 9. Choosing K

We should not simply assume a particular K is best.

Try different values:

```python
k_values = [1, 3, 5, 7, 9, 11, 15, 21]
```

Then compare model performance.

A proper workflow is:

```text
Training Data
      ↓
Cross-Validation
      ↓
Try different K values
      ↓
Choose suitable K
      ↓
Final Test Evaluation
```

The test set should ideally be kept untouched until final evaluation.

---

# 10. Important KNN Hyperparameters

## `n_neighbors`

Controls K.

```python
n_neighbors=5
```

> How many neighbors should be considered?

---

## `weights`

Controls the influence of neighbors.

### `weights="uniform"`

All neighbors have equal influence.

```python
weights="uniform"
```

### `weights="distance"`

Closer neighbors have greater influence.

```python
weights="distance"
```

Easy memory:

```text
uniform  → Equal influence
distance → Closer = more influence
```

---

## `metric`

Controls how distance is calculated.

```python
metric="euclidean"
```

or:

```python
metric="manhattan"
```

Easy memory:

```text
n_neighbors → How many?
weights      → How much influence?
metric       → How is distance calculated?
```

---

# 11. KNN Pipeline

A typical KNN workflow:

```text
Dataset
   ↓
Train/Test Split
   ↓
StandardScaler
   ↓
KNN
   ↓
Tune K / Hyperparameters
   ↓
Evaluate
```

Example:

```python
pipeline = Pipeline([
    ("scaler", StandardScaler()),
    ("knn", KNeighborsClassifier(n_neighbors=5))
])

pipeline.fit(x_train, y_train)

y_train_pred = pipeline.predict(x_train)
y_pred = pipeline.predict(x_test)
```

---

# 12. Our KNN Classification Experiment

Our Iris classification experiment with `K=5` produced:

```text
Train Accuracy = 0.9750
Test Accuracy  = 0.9333
```

The confusion matrix was:

```text
[[10  0  0]
 [ 0 10  0]
 [ 0  2  8]]
```

Therefore:

* Class 0 → 10/10 correct
* Class 1 → 10/10 correct
* Class 2 → 8/10 correct
* Total → 28/30 correct

Test accuracy:

$$
\frac{28}{30}=93.33\%
$$

---

# 13. Our KNN Regression Experiment

With:

```text
K = 5
```

we obtained:

```text
Train R² = 0.9117
Test R²  = 0.8562
MSE      = 1745.1293
```

When testing multiple K values:

```text
K=1  → Test R² = 0.7302
K=3  → Test R² = 0.8432
K=5  → Test R² = 0.8562  ← Best tested
K=7  → Test R² = 0.8477
K=9  → Test R² = 0.8437
K=11 → Test R² = 0.8349
K=15 → Test R² = 0.8226
K=21 → Test R² = 0.8071
```

For this particular experiment, **K=5 performed best among the tested values**.

---

# 14. Computational Cost

KNN can become expensive during prediction because it needs to calculate distances to training samples to identify the nearest neighbors.

As the dataset grows:

```text
Training samples ↑
       ↓
Distance calculations ↑
       ↓
Prediction cost ↑
```

Therefore, KNN may not be ideal for extremely large datasets.

---

# 15. Curse of Dimensionality

KNN can also struggle with **high-dimensional data**.

As the number of features increases:

```text
Features ↑
   ↓
Data becomes sparse in feature space
   ↓
Distance becomes less meaningful
   ↓
KNN performance can decrease
```

Therefore, dimensionality reduction or feature selection may sometimes be useful.

---

# 16. Advantages

* Simple and intuitive
* Easy to implement
* Can model nonlinear relationships
* Works for classification and regression
* Doesn't require a strong assumption of linearity
* Useful for relatively small/medium datasets

---

# 17. Limitations

* Prediction can be computationally expensive
* Sensitive to feature scaling
* Sensitive to irrelevant features
* Choice of K affects performance
* Can suffer from the curse of dimensionality
* Can perform poorly with very large datasets

---

# 18. Classification vs Regression

|            | KNN Classification              | KNN Regression        |
| ---------- | ------------------------------- | --------------------- |
| sklearn    | `KNeighborsClassifier`          | `KNeighborsRegressor` |
| Output     | Class                           | Continuous value      |
| Prediction | Majority vote                   | Average               |
| Metrics    | Accuracy, Precision, Recall, F1 | MSE, RMSE, R²         |
| Example    | Spam / Not Spam                 | House price           |

---

# 19. Final Mental Model

```text
                    KNN
                     │
             Distance-based
                     │
            Find K neighbors
                     │
          ┌──────────┴──────────┐
          ↓                     ↓
   Classification          Regression
          ↓                     ↓
   Majority voting         Average values
          │                     │
          └──────────┬──────────┘
                     ↓
              Important factors
                     │
        ┌────────────┼────────────┐
        ↓            ↓            ↓
        K         Scaling      Distance
        ↓            ↓            ↓
 Bias/Variance   Important   Euclidean etc.
```

## Key Takeaways

* **KNN predicts using nearby training samples.**
* **K = number of neighbors.**
* Classification → **majority vote**.
* Regression → **average target value**.
* KNN is **distance-based**.
* Feature scaling is therefore **very important**.
* Small K → higher variance / overfitting risk.
* Large K → higher bias / underfitting risk.
* `weights="distance"` gives closer neighbors more influence.
* `metric` controls distance calculation.
* KNN can become expensive with large datasets.
* High-dimensional data can cause the **curse of dimensionality**.
* Use **cross-validation** to properly tune K and other hyperparameters.
